name: Crypto Twitter Bot

on:
  schedule:
    # Market updates every 3 hours at :00 (00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, 21:00)
    - cron: '0 */3 * * *'
    # Degen alerts every 3 hours at :30 (00:30, 03:30, 06:30, 09:30, 12:30, 15:30, 18:30, 21:30)  
    - cron: '30 */3 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          echo "Cleaning npm cache..."
          npm cache clean --force
          echo "Installing dependencies..."
          npm install --no-package-lock || npm install --legacy-peer-deps || npm install
      
      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in api/cron/:"
          ls -la api/cron/ || echo "api/cron/ directory not found"
          echo "All files:"
          find . -name "*.js" | head -10
      
      - name: Run market update
        if: github.event.schedule == '0 */3 * * *'
        run: node scripts/run-cron.js market-update
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          CRESTAL_API_KEY: ${{ secrets.CRESTAL_API_KEY }}
          BOT_TWITTER_HANDLE: ${{ secrets.BOT_TWITTER_HANDLE }}
          CRON_SECRET: github-actions
      
      - name: Run degen alert
        if: github.event.schedule == '30 */3 * * *'
        run: node scripts/run-cron.js degen-alert
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          CRESTAL_API_KEY: ${{ secrets.CRESTAL_API_KEY }}
          BOT_TWITTER_HANDLE: ${{ secrets.BOT_TWITTER_HANDLE }}
          CRON_SECRET: github-actions