name: Crypto Twitter Bot

on:
  schedule:
    # Market updates every 5 minutes
    - cron: '*/5 * * * *'
    # Degen alerts every 5 minutes (offset by 2.5 minutes)  
    - cron: '2,7,12,17,22,27,32,37,42,47,52,57 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in api/cron/:"
          ls -la api/cron/ || echo "api/cron/ directory not found"
          echo "All files:"
          find . -name "*.js" | head -10
      
      - name: Run market update
        if: github.event.schedule == '*/5 * * * *'
        run: node api/cron/market-update.js
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          CRESTAL_API_KEY: ${{ secrets.CRESTAL_API_KEY }}
      
      - name: Run degen alert
        if: contains(github.event.schedule, '2,7,12,17,22,27,32,37,42,47,52,57')
        run: node api/cron/degen-alert.js  
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          CRESTAL_API_KEY: ${{ secrets.CRESTAL_API_KEY }}